lib: [
  "META" {"META"}
  "libutp.a" {"libutp.a"}
  "lib/utp.mli" {"utp.mli"}
  "lib/utp.cmi" {"utp.cmi"}
  "utp.cma" {"utp.cma"}
  "utp.cmxa" {"utp.cmxa"}
  "utp-lwt.cma" {"utp-lwt.cma"}
  "utp-lwt.a" {"utp-lwt.a"}
  "utp-lwt.cmxa" {"utp-lwt.cmxa"}
  "lib/utp_lwt.cmi" {"utp_lwt.cmi"}
  "lib/utp_lwt.mli" {"utp_lwt.mli"}
  "utp.a" {"utp.a"}
]
bin: [
  "ucat" {"ucat"}
  "ucat.opt" {"ucat.opt"}
]
doc: [
  "README.md" {"README.md"}
]
