lib: [
  "_build/install/default/lib/utp/META" {"META"}
  "_build/install/default/lib/utp/opam" {"opam"}
  "_build/install/default/lib/utp/utp.cmi"
  "_build/install/default/lib/utp/utp.cmx"
  "_build/install/default/lib/utp/utp.cmt"
  "_build/install/default/lib/utp/utp.cmti"
  "_build/install/default/lib/utp/utp.mli"
  "_build/install/default/lib/utp/utp_lwt.cmi"
  "_build/install/default/lib/utp/utp_lwt.cmx"
  "_build/install/default/lib/utp/utp_lwt.cmt"
  "_build/install/default/lib/utp/utp_lwt.cmti"
  "_build/install/default/lib/utp/utp_lwt.mli"
  "_build/install/default/lib/utp/utp.cma"
  "_build/install/default/lib/utp/libutp_stubs.a"
  "_build/install/default/lib/utp/utp.cmxa"
  "_build/install/default/lib/utp/utp.a"
  "_build/install/default/lib/utp/utp.cmxs"
]
doc: [
  "_build/install/default/doc/utp/README.md"
  "_build/install/default/doc/utp/LICENSE"
]
stublibs: [
  "_build/install/default/lib/stublibs/dllutp_stubs.so"
]
